### ISSUE TITLE
omnic-relayer repository does not exist

### ISSUE THREAD

**Issue by bianyuanop** [rocklabs-io/omnic#30]
Hi,

I want to use this protocol in my project, and i found the omnic-relayer repository does not exists, which makes the protocol not utilizable. Is it possible that you can open that repo?

**Comment by ccyanxyz** [comment]
Relayer will be removed from the architecture in the upcoming upgrade

**Comment by bianyuanop** [comment]
is there any estimated date on the next upgrade?
